name: 'Jacoco Coverage Report'
description: 'Posts Jacoco coverage as a PR comment'
author: 'Luis Hernandez'

branding:
  icon: check-circle
  color: white

inputs:
  github-token:
    description: 'Github token'
    required: false
    default: ${{ github.token }}
  jacoco-xml-path:
    description: 'Path to jacoco.xml file'
    required: false
    default: 'target/site/jacoco/jacoco.xml'
  baseline-path:
    description: ''
    required: false
    default: '.github/jacoco-baseline.json'
  baseline-branch:
    description: ''
    required: false
    default: main
  enable-baseline:
    description: ''
    required: false
    default: "false"

outputs:
  line-coverage:
    description: 'Line coverage percentage'
  branch-coverage:
    description: 'Branch coverage percentage'
  method-coverage:
    description: 'Method coverage percentage'
  complexity-coverage:
    description: 'Complexity coverage percentage'
  class-coverage:
    description: 'Class coverage percentage'
  
runs:
  using: 'node20'
  main: 'dist/main.js'
