import { Baseline, CoverageMetric, ResultCommentParams } from "../types";

function generateNoXmlComment(): string {
  return `## 📊 Code Coverage

Jacoco XML file is not present. 

Are you using this action within a Java/Kotlin repo? 

Make sure you have jacoco in place.`;
}

function generateResultComment({
  metrics,
  ctx,
  baseline,
}: ResultCommentParams): string {
  const tableRows = metrics.map((metric) => {
    const { label, key } = metric.data.output
    const { extractedData } = metric
    return row(label, extractedData, baseline, key)
  }).join('\n')
  
  return `## 📊 Code Coverage

| Type | Covered / Total | Coverage |
|------|----------------|----------|
${tableRows}

<sub>Generated by Jacoco · ${ctx.sha.slice(0, 7)}${baseline ? ` · baseline \`${baseline.sha.slice(0, 7)}\`` : ""}</sub>`;
}

function row(
  label: string,
  d: CoverageMetric | null,
  baseline: Baseline | null,
  key: keyof Baseline,
) {
  if (!d) return `| ${label} | N/A | N/A |`;
  return `| ${label} | ${d.covered} / ${d.covered + d.missed} | **${d.pct}%** ${emoji(d.pct)}${delta(d.pct, baseline, key)} |`;
}

function emoji(pct: number) {
  return pct >= 80 ? "🟢" : pct >= 50 ? "🟡" : "🔴";
}

function delta(
  current: number,
  baseline: Baseline | null,
  key: keyof Baseline,
): string {
  if (!baseline || typeof baseline[key] !== "number") return "";
  const diff = +(current - (baseline[key] as number)).toFixed(1);
  if (diff > 0) return ` ▲ +${diff}%`;
  if (diff < 0) return ` ▼ ${diff}%`;
  return " ─";
}

export {
    generateNoXmlComment,
    generateResultComment
}