import { readFileSync } from "fs";

import * as core from "@actions/core";
import { context, getOctokit } from "@actions/github";

import {
  Baseline,
  CoverageMetric,
  CoverageResult,
  ProccessedMetric,
  ResultCommentParams,
} from "./types";

import { ACTION_INPUTS, METRIC_FIELDS } from "./utils";

// Logic impl

function safeRun<T>(cb: Function): T | null {
  try {
    const result = cb();
    return result;
  } catch {
    return null;
  }
}

function generateNoXmlComment(): string {
  return `## 📊 Code Coverage

Jacoco XML file is not present. 

Are you using this action within a Java/Kotlin repo? 

Make sure you have jacoco in place.`;
}

function generateResultComment({
  metrics,
  ctx,
  baseline,
}: ResultCommentParams): string {
  const tableRows = metrics.map((metric) => {
    const { label, key } = metric.data.output
    const { extractedData } = metric
    return row(label, extractedData, baseline, key)
  }).join('\n')
  
  return `## 📊 Code Coverage

| Type | Covered / Total | Coverage |
|------|----------------|----------|
${tableRows}

<sub>Generated by Jacoco · </sub>`;
}

function emoji(pct: number) {
  return pct >= 80 ? "🟢" : pct >= 50 ? "🟡" : "🔴";
}

function delta(
  current: number,
  baseline: Baseline | null,
  key: keyof Baseline,
): string {
  if (!baseline || typeof baseline[key] !== "number") return "";
  const diff = +(current - (baseline[key] as number)).toFixed(1);
  if (diff > 0) return ` ▲ +${diff}%`;
  if (diff < 0) return ` ▼ ${diff}%`;
  return " ─";
}

function row(
  label: string,
  d: CoverageMetric | null,
  baseline: Baseline | null,
  key: keyof Baseline,
) {
  if (!d) return `| ${label} | N/A | N/A |`;
  return `| ${label} | ${d.covered} / ${d.covered + d.missed} | **${d.pct}%** ${emoji(d.pct)}${delta(d.pct, baseline, key)} |`;
}

function extract(xml: string, type: string): CoverageResult {
  console.log(type)
  const re = new RegExp(
    `<counter type="${type}" missed="(\\d+)" covered="(\\d+)"`,
    "g",
  );
  const matches = [...xml.matchAll(re)];
  const m = matches.at(-1);
  if (!m) return null;
  const missed = +m[1],
    covered = +m[2];
  return {
    missed,
    covered,
    pct: +((covered / (covered + missed)) * 100).toFixed(1),
  };
}

async function publishComment(
  content: string,
  // octokit: ReturnType<typeof getOctokit>,
) {
  const prNumber = context.payload.pull_request?.number ?? 9999;

  if (!prNumber) {
    core.warning("Not running in a PR context, skipping comment");
    return;
  }

  console.log(content)

  // const { data: comments } = await octokit.rest.issues.listComments({
  //   ...context.repo,
  //   issue_number: prNumber,
  // });
  // const prev = comments.find((c) => c.body?.includes("📊 Code Coverage"));

  // if (prev) {
  //   await octokit.rest.issues.deleteComment({
  //     ...context.repo,
  //     comment_id: prev.id,
  //   });
  // }

  // await octokit.rest.issues.createComment({
  //   ...context.repo,
  //   issue_number: prNumber,
  //   body: content,
  // });
}

function publishActionOutput(metricData: ProccessedMetric[]) {
  metricData.forEach(metric => {
    if (metric.extractedData) {
      core.setOutput(metric.data.output.name, metric.extractedData.pct)
    }
  })
}

// TODO: Define approach to get baseline
// function getBaseLine(): Baseline {
//   return { line: 0, branch: 0, method: 0, sha: '' }
// }

async function run() {
  // const xmlPath = core.getInput(ACTION_INPUTS.JACOCO_XML_PATH);
  // const token = core.getInput(ACTION_INPUTS.GITHUB_TOKEN);

  // const octokit = getOctokit(token);

  let commentContent: string | undefined = undefined;

  const xmlPath = "target/site/jacoco/jacoco.xml"

  const xml: string | null = safeRun(() => readFileSync(xmlPath, "utf-8"));

  if (!xml) {
    commentContent = generateNoXmlComment();
  } else {
    const processedMetricData: ProccessedMetric[] = METRIC_FIELDS.map(metric => {
      return {
        data: metric,
        extractedData: extract(xml, metric.xmlField)
      }
    })

    // console.log(processedMetricData)

    publishActionOutput(processedMetricData)

    const baseline = null;

    commentContent = generateResultComment({
      metrics: processedMetricData,
      ctx: context,
      baseline,
    });
  }

  await publishComment(commentContent);
}

run().catch(core.setFailed);
