import { readFileSync } from 'fs';

import * as core from '@actions/core';
import { context, getOctokit } from '@actions/github';

// Types definition
type CoverageResult = CoverageMetric | null


interface CoverageMetric {
  missed: number,
  covered: number,
  pct: number
}

interface Baseline {
  line: number,
  branch: number,
  method: number,
  sha: string
}

interface ResultCommentParams {
  line: CoverageResult,
  branch: CoverageResult,
  method: CoverageResult,
  baseline: Baseline,
  ctx: typeof context
}

// Logic impl

const METRIC_FIELDS = [
  'LINE',
  'BRANCH',
  'METHOD'
]

function safeRun<T>(cb: Function): T | null {
  try {
    const result = cb()
    return result
  } catch {
    return null
  }
}

function generateNoXmlComment(): string {
  return `## 📊 Code Coverage

            Jacoco XML file is not present. 
            
            Are you using this action within a Java/Kotlin repo? 

            Make sure you have jacoco in place.`;
}

function generateResultComment({ line, branch, method, ctx, baseline }: ResultCommentParams): string {
  return `## 📊 Code Coverage

            | Type | Covered / Total | Coverage |
            |------|----------------|----------|
            ${row('Lines', line, baseline, 'line')}
            ${row('Branches', branch, baseline, 'branch')}
            ${row('Methods', method, baseline, 'method')}

            <sub>Generated by Jacoco · ${ctx.sha.slice(0, 7)}${baseline ? ` · baseline \`${baseline.sha.slice(0, 7)}\`` : ''}</sub>`;
}

function emoji(pct: number) {
  return pct >= 80 ? '🟢' : pct >= 50 ? '🟡' : '🔴';
}

function delta(current: number, baseline: Baseline | null, key: keyof Baseline): string {
  if (!baseline || typeof baseline[key] !== 'number') return '';
  const diff = +(current - (baseline[key] as number)).toFixed(1);
  if (diff > 0) return ` ▲ +${diff}%`;
  if (diff < 0) return ` ▼ ${diff}%`;
  return ' ─';
}

function row(label: string, d: CoverageMetric | null, baseline: Baseline | null, key: keyof Baseline) {
  if (!d) return `| ${label} | N/A | N/A |`;
  return `| ${label} | ${d.covered} / ${d.covered + d.missed} | **${d.pct}%** ${emoji(d.pct)}${delta(d.pct, baseline, key)} |`;
}

function extract(xml: string, type: string): CoverageResult {
  const re = new RegExp(`<counter type="${type}" missed="(\\d+)" covered="(\\d+)"`, 'g');
  const matches = [...xml.matchAll(re)];
  const m = matches.at(-1);
  if (!m) return null;
  const missed = +m[1], covered = +m[2];
  return { missed, covered, pct: +((covered / (covered + missed)) * 100).toFixed(1) };
}

async function publishComment(content: string, octokit: ReturnType<typeof getOctokit>) {
  const prNumber = context.payload.pull_request?.number

  if (!prNumber) {
    core.warning("Not running in a PR context, skipping comment")
    return
  }

  const { data: comments } = await octokit.rest.issues.listComments({ ...context.repo, issue_number: prNumber })
  const prev = comments.find(c => c.body?.includes('📊 Code Coverage'))

  if (prev) {
    await octokit.rest.issues.deleteComment({ ...context.repo, comment_id: prev.id })
  }

  await octokit.rest.issues.createComment({ ...context.repo, issue_number: prNumber, body: content })
}

// TODO: Define approach to get baseline
function getBaseLine(): Baseline {
  return { line: 0, branch: 0, method: 0, sha: '' }
}

async function run() {
  const xmlPath = core.getInput('jacoco-xml-path');
  const token = core.getInput('github-token');

  const octokit = getOctokit(token);

  let commentContent: string | undefined = undefined;

  const xml: string | null = safeRun(() => readFileSync(xmlPath, 'utf-8'));

  if (!xml) {
    commentContent = generateNoXmlComment();
  } else {
    const [line, branch, method] = METRIC_FIELDS.map(field => extract(xml, field))

    if (line) core.setOutput('line-coverage', line.pct)
    if (branch) core.setOutput('branch-coverage', branch.pct)
    if (method) core.setOutput('method-coverage', method.pct)

    const baseline = getBaseLine()

    commentContent = generateResultComment({
      line,
      branch,
      method,
      ctx: context,
      baseline
    })
  }

  await publishComment(commentContent, octokit)

}

run().catch(core.setFailed)