name: Test action

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Post coverage comment
        uses: ./
        with:
          github-token: ${{ github.token }}
          enable-baseline: true
